# Documentation: http://docs.travis-ci.com/user/languages/julia/
language: julia
coveralls: true
codecov: true
os:
  - linux
  - osx
julia:
  - 1
addons:
  apt_packages:
    - libgmp-dev
notifications:
  email: false
